export const GET_ALL_COUNTRIES ='GET_ALL_COUNTRIES';
export const GET_COUNTRY_BY_NAME ='GET_COUNTRY_BY_NAME';
export const GET_COUNTRY_DETAILS ='GET_COUNTRY_DETAILS';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const GET_ACTIVITY ='GET_ACTIVITY';
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';
export const FILTER_BY_ACTIVITY = 'FILTER_BY_ACTIVITY';
export const FILTER_ACT_BY_SEASON = 'FILTER_ACT_BY_SEASON';
export const SORT_COUNTRIES ='SORT_COUNTRIES';
export const SORT_BY_AREA = 'SORT_BY_AREA';

